aws_access_key = "AKIAZI2LH7QOSEYG3WFG"
aws_secret_key = "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"
aws_region = "us-east-1"
vpc_cidr = "10.1.0.0/16"
vpc_name = "terraform-aws-testing"
environment = "dev"
